// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpGs4Xxeo-LFIRMyUbiyuwk_YUo0wNzdI',
    appId: '1:890643987520:web:f1cc8ac9e16e7c92f0f3a5',
    messagingSenderId: '890643987520',
    projectId: 'myclasses-3c9e2',
    authDomain: 'myclasses-3c9e2.firebaseapp.com',
    storageBucket: 'myclasses-3c9e2.firebasestorage.app',
    measurementId: 'G-YPVS7RN8V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalKFizyVOiSsZtIvKU9tcPLJHtPmC_bc',
    appId: '1:890643987520:android:cacb5be3ccce5db5f0f3a5',
    messagingSenderId: '890643987520',
    projectId: 'myclasses-3c9e2',
    storageBucket: 'myclasses-3c9e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVy6Dnnb-rlM2xRCkoeIBW1HiDKzKxgQU',
    appId: '1:890643987520:ios:f83146ce5af726c8f0f3a5',
    messagingSenderId: '890643987520',
    projectId: 'myclasses-3c9e2',
    storageBucket: 'myclasses-3c9e2.firebasestorage.app',
    iosBundleId: 'com.example.myClasses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVy6Dnnb-rlM2xRCkoeIBW1HiDKzKxgQU',
    appId: '1:890643987520:ios:f83146ce5af726c8f0f3a5',
    messagingSenderId: '890643987520',
    projectId: 'myclasses-3c9e2',
    storageBucket: 'myclasses-3c9e2.firebasestorage.app',
    iosBundleId: 'com.example.myClasses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpGs4Xxeo-LFIRMyUbiyuwk_YUo0wNzdI',
    appId: '1:890643987520:web:817fbff443bc58fcf0f3a5',
    messagingSenderId: '890643987520',
    projectId: 'myclasses-3c9e2',
    authDomain: 'myclasses-3c9e2.firebaseapp.com',
    storageBucket: 'myclasses-3c9e2.firebasestorage.app',
    measurementId: 'G-NQCF41RREH',
  );
}
