name: Build & Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install NDK
        run: sdkmanager "ndk;29.0.13599879"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2"
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Patch Isar namespace
        run: |
          FILE="$HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.1.0+1/android/build.gradle"

          if [ -f "$FILE" ]; then
            sed -i '/android {/a\    namespace "dev.isar.isar_flutter_libs"' "$FILE"
            echo "Isar namespace patched"
          else
            echo "Isar build.gradle not found"
            find $HOME/.pub-cache -name build.gradle | grep isar || true
            exit 1
          fi

      - name: Create .env file from secrets
        run: |
          echo "MY_CLASSES_URL=${{ secrets.MY_CLASSES_URL }}" >> .env
          echo "MY_CLASSES_ANON_KEY=${{ secrets.MY_CLASSES_ANON_KEY }}" >> .env

      - name: Build APK
        run: flutter build apk --release --obfuscate --split-debug-info=build/debug_info --split-per-abi

      - name: Upload APK to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}